name: Update Tweets

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-tweets:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r server/requirements.txt
    
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest
    
    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1-3)
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
        wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
    
    - name: Run scraping script
      env:
        TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }}
        TWITTER_PASSWORD: ${{ secrets.TWITTER_PASSWORD }}
      run: |
        echo "TWITTER_USERNAME is set: ${{ secrets.TWITTER_USERNAME != '' }}"
        echo "TWITTER_PASSWORD is set: ${{ secrets.TWITTER_PASSWORD != '' }}"
        python server/scrape_tweet.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions@example.com"
        git config --global user.name "GitHub Actions"
        git add client/WaterCodes.json
        git commit -m "Update tweets" || exit 0
        git push