name: Update Tweets

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:  

jobs:
  update-tweets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'
    - name: Install dependencies
      run: |
        python -m pip3 install --upgrade pip
        pip3 install -r server/requirements.txt
        pip3 install selenium
    - name: Run scraping script
      env:
        TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }}
        TWITTER_PASSWORD: ${{ secrets.TWITTER_PASSWORD }}
        pythonLocation: /opt/hostedtoolcache/Python/3.12.4/x64
        PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.4/x64/lib/pkgconfig
        Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.4/x64
        Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.4/x64
        Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.4/x64
        LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.4/x64/lib
      run: |
        python server/scrape_tweet.py
      shell: /usr/bin/bash -e {0}
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions@example.com"
        git config --global user.name "GitHub Actions"
        git add client/WaterCodes.json
        git commit -m "Update tweets" || exit 0
        git push